# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sh-pointlist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sh-pointlist.proto\x12\x0bsmokyhumans\"\x1b\n\tPointList\x12\x0e\n\x06points\x18\x01 \x03(\x02\"\x07\n\x05\x45mpty2H\n\x0bSmokyHumans\x12\x39\n\tGetPoints\x12\x12.smokyhumans.Empty\x1a\x16.smokyhumans.PointList\"\x00\x62\x06proto3')



_POINTLIST = DESCRIPTOR.message_types_by_name['PointList']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
PointList = _reflection.GeneratedProtocolMessageType('PointList', (_message.Message,), {
  'DESCRIPTOR' : _POINTLIST,
  '__module__' : 'sh_pointlist_pb2'
  # @@protoc_insertion_point(class_scope:smokyhumans.PointList)
  })
_sym_db.RegisterMessage(PointList)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'sh_pointlist_pb2'
  # @@protoc_insertion_point(class_scope:smokyhumans.Empty)
  })
_sym_db.RegisterMessage(Empty)

_SMOKYHUMANS = DESCRIPTOR.services_by_name['SmokyHumans']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTLIST._serialized_start=35
  _POINTLIST._serialized_end=62
  _EMPTY._serialized_start=64
  _EMPTY._serialized_end=71
  _SMOKYHUMANS._serialized_start=73
  _SMOKYHUMANS._serialized_end=145
# @@protoc_insertion_point(module_scope)
