# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sh_pointlist_pb2 as sh__pointlist__pb2


class SmokyHumansStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoints = channel.unary_unary(
                '/smokyhumans.SmokyHumans/GetPoints',
                request_serializer=sh__pointlist__pb2.Empty.SerializeToString,
                response_deserializer=sh__pointlist__pb2.PointList.FromString,
                )


class SmokyHumansServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmokyHumansServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoints,
                    request_deserializer=sh__pointlist__pb2.Empty.FromString,
                    response_serializer=sh__pointlist__pb2.PointList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smokyhumans.SmokyHumans', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SmokyHumans(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smokyhumans.SmokyHumans/GetPoints',
            sh__pointlist__pb2.Empty.SerializeToString,
            sh__pointlist__pb2.PointList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
